extends Node2D
class_name FreeCameraComponent

@onready var camera: GameCamera = $GameCamera

func _ready() -> void:
	var map_size_x: int = Global.TILE_SIZE * (Global.ROOM_WIDTH * Global.GRID_WIDTH)
	var map_size_y: int = Global.TILE_SIZE * (Global.ROOM_HEIGHT * Global.GRID_HEIGHT)

	Log.pr("Map size: ", map_size_x, map_size_y)

	camera.set_limit(SIDE_LEFT, -100)
	camera.set_limit(SIDE_TOP, -100)
	camera.set_limit(SIDE_RIGHT, map_size_x + 100)
	camera.set_limit(SIDE_BOTTOM, map_size_y + 100)

	pass
